#!/bin/bash
# Experiment 7: N≠M — Transformer+G across (N,M) pairs where M > N.
# 3 configs × 3 seeds = 9 tasks.
#
# Pre-requisite: data/{n2m4,n3m6,n2m6}_8x8_G generated by scripts/gen_nm_data.sh
# Chain: sbatch --dependency=afterok:<gen_job_id> scripts/exp_nm.sh
# Aggregate per config:
#   python compare.py --pattern "nm_n2m4_*" --data_dir ../data/n2m4_8x8_G
#   python compare.py --pattern "nm_n3m6_*" --data_dir ../data/n3m6_8x8_G
#   python compare.py --pattern "nm_n2m6_*" --data_dir ../data/n2m6_8x8_G

#SBATCH --job-name=mcpf_nm
#SBATCH --partition=rtx3090
#SBATCH --account=erant
#SBATCH --qos=erant
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --array=0-8
#SBATCH --output=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_nm_%A_%a.out
#SBATCH --error=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_nm_%A_%a.err

set -euo pipefail

PROJECT=/home/dayanb/course_multiagent/Neural_MCPF_Allocation

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate mcpf_env

# task_id = config_idx*3 + seed_idx
CONFIGS=("2 4 n2m4" "3 6 n3m6" "2 6 n2m6")
SEEDS=(0 1 2)

CONFIG=${CONFIGS[$((SLURM_ARRAY_TASK_ID / 3))]}
SEED=${SEEDS[$((SLURM_ARRAY_TASK_ID % 3))]}

N=$(echo "$CONFIG" | awk '{print $1}')
M=$(echo "$CONFIG" | awk '{print $2}')
TAG=$(echo "$CONFIG" | awk '{print $3}')
DATA_DIR="$PROJECT/data/${TAG}_8x8_G"
RUN_NAME="nm_${TAG}_s${SEED}"

echo "Task $SLURM_ARRAY_TASK_ID: N=$N M=$M tag=$TAG seed=$SEED"

cd "$PROJECT/training"
python train.py \
    --model_type transformer \
    --N "$N" --M "$M" \
    --hidden 64 --num_heads 4 --num_layers 3 \
    --epochs 100 --batch_size 256 --lr 1e-3 --lam 0.1 \
    --use_goal_dists \
    --seed "$SEED" \
    --data_dir "$DATA_DIR" \
    --run_name "$RUN_NAME"

cd "$PROJECT/evaluation"
python evaluate.py \
    --checkpoint "$PROJECT/checkpoints/${RUN_NAME}/best.pt" \
    --data_dir   "$DATA_DIR" \
    --split test
