#!/bin/bash
# Train GoalAllocTransformerUniversal on all 15 N×M configs jointly.
# 3 seeds (array tasks 0-2).
#
# Pre-requisite: data/universal_8x8/n{N}m{M}/ generated by gen_universal_data.sh
# Chain: sbatch --dependency=afterok:<gen_job_id> scripts/exp_universal.sh
#
# Aggregate (evaluate on a specific config):
#   python evaluation/compare.py --pattern "universal_*" \
#       --data_dir data/universal_8x8/n3m3

#SBATCH --job-name=mcpf_universal
#SBATCH --partition=rtx3090
#SBATCH --account=erant
#SBATCH --qos=erant
#SBATCH --time=06:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --gres=gpu:1
#SBATCH --array=0-2
#SBATCH --output=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_universal_%A_%a.out
#SBATCH --error=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_universal_%A_%a.err

set -euo pipefail

PROJECT=/home/dayanb/course_multiagent/Neural_MCPF_Allocation
UDATA="$PROJECT/data/universal_8x8"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate mcpf_env

SEED=$SLURM_ARRAY_TASK_ID
RUN_NAME="universal_s${SEED}"
echo "Task $SLURM_ARRAY_TASK_ID: universal model seed=$SEED"

# Build comma-separated list of all 15 data dirs
DATA_DIRS=""
for N in 2 3 4; do
    for M in 2 3 4 5 6; do
        DIR="$UDATA/n${N}m${M}"
        DATA_DIRS="${DATA_DIRS:+$DATA_DIRS,}$DIR"
    done
done

cd "$PROJECT/training"
python train.py \
    --model_type transformer \
    --hidden 64 --num_heads 4 --num_layers 3 \
    --use_goal_dists \
    --mixed \
    --data_dirs "$DATA_DIRS" \
    --epochs 100 --batch_size 256 --lr 1e-3 --lam 0.1 \
    --seed "$SEED" \
    --run_name "$RUN_NAME"

# Evaluate on each N=M config to compare against per-size baselines
cd "$PROJECT/evaluation"
for N in 2 3 4; do
    echo "--- Eval N=M=$N ---"
    python evaluate.py \
        --checkpoint "$PROJECT/checkpoints/${RUN_NAME}/best.pt" \
        --data_dir   "$UDATA/n${N}m${N}" \
        --split test
done
