#!/bin/bash
# Experiment 5: Goal-goal distance ablation — transformer ±G at N∈{2,3,4}, 8×8
# 3 N values × 2 variants (noG / G) × 3 seeds = 18 tasks
#
# Pre-requisite: data/n{2,3,4}_8x8_G generated by scripts/gen_scale_data_g.sh
# Chain:         sbatch --dependency=afterok:<gen_job_id> scripts/exp_goal_dists.sh

#SBATCH --job-name=mcpf_goaldists
#SBATCH --partition=rtx3090
#SBATCH --account=erant
#SBATCH --qos=erant
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --array=0-17
#SBATCH --output=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_gd_%A_%a.out
#SBATCH --error=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_gd_%A_%a.err

set -euo pipefail

PROJECT=/home/dayanb/course_multiagent/Neural_MCPF_Allocation

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate mcpf_env

N_VALUES=(2 3 4)
USE_G=(0 1)       # 0 = no goal-goal dists, 1 = with goal-goal dists
SEEDS=(0 1 2)

# task_id = n_idx*6 + g_idx*3 + seed_idx
N=${N_VALUES[$((SLURM_ARRAY_TASK_ID / 6))]}
G_FLAG=${USE_G[$(((SLURM_ARRAY_TASK_ID % 6) / 3))]}
SEED=${SEEDS[$((SLURM_ARRAY_TASK_ID % 3))]}
DATA_DIR="$PROJECT/data/n${N}_8x8_G"

if [ "$G_FLAG" -eq 1 ]; then
    VARIANT="G"
    EXTRA_ARGS="--use_goal_dists"
else
    VARIANT="noG"
    EXTRA_ARGS=""
fi

RUN_NAME="gd_n${N}_${VARIANT}_s${SEED}"
echo "Task $SLURM_ARRAY_TASK_ID: N=$N variant=$VARIANT seed=$SEED"

cd "$PROJECT/training"
# shellcheck disable=SC2086
python train.py \
    --model_type transformer \
    --N "$N" --M "$N" \
    --hidden 64 --num_heads 4 --num_layers 3 \
    --epochs 100 --batch_size 256 --lr 1e-3 --lam 0.1 \
    --seed "$SEED" \
    --data_dir "$DATA_DIR" \
    --run_name "$RUN_NAME" \
    $EXTRA_ARGS

cd "$PROJECT/evaluation"
python evaluate.py \
    --checkpoint "$PROJECT/checkpoints/${RUN_NAME}/best.pt" \
    --data_dir   "$DATA_DIR" \
    --split test
