#!/bin/bash
# Experiment 6: Transformer + G at N=5, 8×8 — completes the N-scaling story
# 3 seeds
#
# Pre-requisite: data/n5_8x8_G generated by scripts/gen_scale_data_g.sh
# Chain: sbatch --dependency=afterok:<gen_job_id> scripts/exp_g_n5.sh
# Aggregate: python compare.py --pattern "gn5_*" --data_dir ../data/n5_8x8_G

#SBATCH --job-name=mcpf_g_n5
#SBATCH --partition=rtx3090
#SBATCH --account=erant
#SBATCH --qos=erant
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --array=0-2
#SBATCH --output=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_gn5_%A_%a.out
#SBATCH --error=/home/dayanb/course_multiagent/Neural_MCPF_Allocation/logs/exp_gn5_%A_%a.err

set -euo pipefail

PROJECT=/home/dayanb/course_multiagent/Neural_MCPF_Allocation
DATA_DIR="$PROJECT/data/n5_8x8_G"

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate mcpf_env

SEED=$SLURM_ARRAY_TASK_ID
RUN_NAME="gn5_G_s${SEED}"
echo "Task $SLURM_ARRAY_TASK_ID: N=5 +G seed=$SEED"

cd "$PROJECT/training"
python train.py \
    --model_type transformer \
    --N 5 --M 5 \
    --hidden 64 --num_heads 4 --num_layers 3 \
    --epochs 100 --batch_size 256 --lr 1e-3 --lam 0.1 \
    --use_goal_dists \
    --seed "$SEED" \
    --data_dir "$DATA_DIR" \
    --run_name "$RUN_NAME"

cd "$PROJECT/evaluation"
python evaluate.py \
    --checkpoint "$PROJECT/checkpoints/${RUN_NAME}/best.pt" \
    --data_dir   "$DATA_DIR" \
    --split test
